title: John Obelenus
baseline: Keeping the chaos at bay
description: Solving Problems & Saving Time through Software and Crushing Entropy
baseurl: /
canonicalurl: true
theme: hyde
date:
  format: j F Y
  timezone: US/Eastern
pagination:
  max: 5
  path: page
output:
  formats:
    netlify_redirects:
      extension: ''
      mediatype: text/plain
virtualpages:
  _redirects:
    output: netlify_redirects
  admin:
    layout: admin/index
    title: Content Manager (Netlify CMS)
    output: html
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
